[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH=$PATH:~/.cargo/bin
[[ -e $(which path) ]] && export PATH=$(path sort -s ~/.path/sort.json)

# Start keychain as our ssh-agent, using AddKeysToAgent in ~/.ssh/config
[[ -e $(which keychain) ]] && eval $(keychain --eval --quiet --noask --agents ssh)
